### ISSUE TITLE
datenwaben.de

### ISSUE THREAD

**Issue by exmatrikulator** [tursics/data-dashboard#11]
Do you like to host the project at datenwaben.de?

**Comment by tursics** [comment]
That's a good idea

**Comment by tursics** [comment]
Done. Registered a new domain, copied the data of Wuppertal, and created a new twitter handle.

**Comment by exmatrikulator** [comment]
perfect!
Thanks ;)

**Comment by derhuerst** [comment]
What is the Twitter handle?

**Comment by tursics** [comment]
https://twitter.com/datenwaben
